import Head from "next/head";
// import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [click, setClick] = useState(false);
  const [firstClick, setFirstClick] = useState(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.frame}>
          <div className={styles.center}>
            <div
              className={`${styles.menuIcon} ${click && styles.active}`}
              onClick={() => {
                setClick(!click);
                setFirstClick(true);
              }}
            >
              <div
                className={`${styles.line1} ${
                  firstClick ? "" : styles.noAnimation
                }`}
              />
              <div
                className={`${styles.line2} ${
                  firstClick ? "" : styles.noAnimation
                }`}
              />
              <div
                className={`${styles.line3} ${
                  firstClick ? "" : styles.noAnimation
                }`}
              />
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
